spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Notification
server:
  port: 8081



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
