  server:
    port: 8080
  spring:
    application:
      name: proxy
    cloud:
      gateway:
        routes:
          - id: user-service
            uri: lb://USER
            predicates:
              - Path=/users/**
          - id: order-service
            uri: http://localhost:8082/
            predicates:
              - Path=/orders/**
          - id: products-service
            uri: lb://PRODUCTS
            predicates:
              - Path=/products/**
          - id: payment-service
            uri: lb://PAYMENT
            predicates:
              - Path=/payment/**
          - id: reporting-service
            uri: lb://REPORTING
            predicates:
              - Path=/reporting/**
          - id: notification-service
            uri: lb://NOTIFICATION
            predicates:
              - Path=/notification/**

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/