  server:
    port: 8080
  spring:
    application:
      name: proxy
    cloud:
      gateway:
        routes:
          - id: user-service
            uri: lb://USER
            predicates:
              - Path=/users/**
          - id: order-service
            uri: http://localhost:8082/
            predicates:
              - Path=/orders/**
          - id: customer-service
            uri: http://localhost:8082/
            predicates:
              - Path=/customers/**

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/